
INSERT INTO IconDefinitions
			(`Name`,					Atlas,`Index`)
VALUES		('ICON_UNIT_CN_TRILOGY_FOW',		'ICON_ATLAS_UNITS_FOW','34');


INSERT INTO IconDefinitions
			(`Name`,					Atlas,`Index`)
VALUES		('ICON_UNIT_CN_TRILOGY',		'ICON_ATLAS_UNITS','34');

-- 插入 ICON_UNIT_SWORDSMAN_PORTRAIT 的记录
INSERT INTO IconDefinitions (`Name`, `Atlas`, `Index`)
VALUES ('ICON_UNIT_CN_TRILOGY_PORTRAIT', 'ICON_ATLAS_UNIT_PORTRAITS', 32);

-- 插入 ICON_ETHNICITY_ASIAN_UNIT_SWORDSMAN_PORTRAIT 的记录
INSERT INTO IconDefinitions (`Name`, `Atlas`, `Index`)
VALUES ('ICON_ETHNICITY_ASIAN_UNIT_CN_TRILOGY_PORTRAIT', 'ICON_ATLAS_ASIAN_UNIT_PORTRAITS', 32);

-- 插入 ICON_ETHNICITY_MEDIT_UNIT_SWORDSMAN_PORTRAIT 的记录
INSERT INTO IconDefinitions (`Name`, `Atlas`, `Index`)
VALUES ('ICON_ETHNICITY_MEDIT_UNIT_CN_TRILOGY_PORTRAIT', 'ICON_ATLAS_MEDITERRANEAN_UNIT_PORTRAITS', 32);

-- 插入 ICON_ETHNICITY_SOUTHAM_UNIT_SWORDSMAN_PORTRAIT 的记录
INSERT INTO IconDefinitions (`Name`, `Atlas`, `Index`)
VALUES ('ICON_ETHNICITY_SOUTHAM_UNIT_CN_TRILOGY_PORTRAIT', 'ICON_ATLAS_SOUTH_AMERICAN_UNIT_PORTRAITS', 32);

-- 插入 ICON_ETHNICITY_AFRICAN_UNIT_SWORDSMAN_PORTRAIT 的记录
INSERT INTO IconDefinitions (`Name`, `Atlas`, `Index`)
VALUES ('ICON_ETHNICITY_AFRICAN_UNIT_CN_TRILOGY_PORTRAIT', 'ICON_ATLAS_AFRICAN_UNIT_PORTRAITS', 32);

-- 插入 ICON_UNIT_SWORDSMAN_WHITE 的记录
INSERT INTO IconDefinitions (`Name`, `Atlas`, `Index`)
VALUES ('ICON_UNIT_CN_TRILOGY_WHITE', 'ICON_ATLAS_UNIT_FLAG_SYMBOLS_WHITE', 34);

-- 插入 ICON_UNIT_SWORDSMAN_BLACK 的记录
INSERT INTO IconDefinitions (`Name`, `Atlas`, `Index`)
VALUES ('ICON_UNIT_CN_TRILOGY_BLACK', 'ICON_ATLAS_UNIT_FLAG_SYMBOLS_BLACK', 34);